language: python
arch:
    - amd64
    - ppc64le

dist: bionic

python:
    - 2.7
    - 3.4
    - 3.7
    - 3.8
    - pypy2.7-6.0

env:
    - KAFKA_VERSION=0.8.2.2
    - KAFKA_VERSION=0.9.0.1
    - KAFKA_VERSION=0.10.2.2
    - KAFKA_VERSION=0.11.0.3
    - KAFKA_VERSION=1.1.1
    - KAFKA_VERSION=2.4.0
    - KAFKA_VERSION=2.5.0
    - KAFKA_VERSION=2.6.0
jobs:
  exclude:
    - arch : ppc64le
      python :  
            - "2.7"
    - arch : ppc64le
      python :  
            - "3.4"
    - arch : ppc64le
      python :  
            - "pypy2.7-6.0"
            
addons:
  apt:
    packages:
      - libsnappy-dev
      - libzstd-dev
      - openjdk-8-jdk

cache:
  directories:
    - $HOME/.cache/pip
    - servers/dist

before_install:
    - source travis_java_install.sh
    - ./build_integration.sh

install:
    - pip install tox coveralls
    - pip install .

script:
  - tox -e `if [ "$TRAVIS_PYTHON_VERSION" == "pypy2.7-6.0" ]; then echo pypy; else echo py${TRAVIS_PYTHON_VERSION/./}; fi`

after_success:
  - coveralls
